dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - chmod +x scripts/test.sh
  - chmod +x scripts/coverage.sh
before_script:
  - truffle version
script:
  - npm run lint
  - npm run test
  - npm run coverage

